name: Qt Client CI

on:
  push:
  pull_request:

env:
  PYTHON_VERSION: "3.14"
  QT_VERSION: 6.4.2
  CMAKE_VERSION: 4.2.3
  NINJA_VERSION: 1.13.2
  GCC_VERSION: 13.2.0
  LLVM_VERSION: 21.1.8
  CPPCHECK_VERSION: 2.19.0

jobs:
  # Job 1: Linting (Clang-Format, Tidy, Cppcheck)
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ env.CMAKE_VERSION }}

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: ${{ env.NINJA_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_mingw_64
          modules: "qtdeclarative qttools"
          cache: true

      - name: Install LLVM
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ env.LLVM_VERSION }}
          platform: x64

      - name: Install CPPCheck
        run: |
          choco install cppcheck --version=${{ env.CPPCHECK_VERSION }} --no-progress

      - name: Run linting
        run: |
          $env:QT_DIR = "${{ env.Qt6_DIR }}"
          python manage.py build debug
          python manage.py lint

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [debug, release]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ env.CMAKE_VERSION }}

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: ${{ env.NINJA_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_mingw_64
          modules: "qtdeclarative qttools"
          cache: true

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: build-${{ matrix.build_type }}
          key: ${{ runner.os }}-qt-${{ env.QT_VERSION }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Build
        run: |
          $env:QT_DIR = "${{ env.Qt6_DIR }}"
          python manage.py build ${{ matrix.build_type }}